import { useState } from 'react';

import Head from 'next/head';
import styles from '../styles/Home.module.css';

import TextField from '@mui/material/TextField';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';
import Button from '@mui/material/Button';

import Link from 'next/link';

export default function Home() {
  const [data, setData] = useState([]);

  const getData = async () => {
    fetch('http://127.0.0.1:8000/get-data', { method: 'GET' })
      .then((response) => response.json())
      .then((data) => {
        console.log(data.data);
        setData(data.data);
      })
      .catch((error) => {
        console.error('Error:', error);
      });
  }

  const deleteData = async () => {
    alert("Delete data...");
  }

  const formSubmit = async (e) => {
    const formData = new FormData();
    formData.append("fname", document.getElementById("fname").value);
    formData.append("lname", document.getElementById("lname").value);
    formData.append("email", document.getElementById("email").value);
    formData.append("password", document.getElementById("pwd").value);
    formData.append("gender", document.getElementById("gender").value);
    formData.append("photo", document.getElementById("photo").files[0]);

    fetch('http://127.0.0.1:8000/register', {
      method: 'POST',
      body: formData,
    })
    .then((response) => response.json())
    .then((data) => {
      if (data['status'] === "OK") {
        alert("Successfully created a new user");
      } else {
        alert("Something went wrong, please try again !!!")
      }
    })
    .catch((error) => {
      console.error('Error:', error);
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>SAYED</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Get a <a href="https://nextjs.org">account !</a>
        </h1>

        <div>
          <Box
            sx={{
              '& .MuiTextField-root': { m: 1, width: '25ch' },
            }}
            noValidate
            autoComplete="off"
          >
            <form>
              <Grid>
                <Grid item xs={6}>
                  <TextField
                    id="fname"
                    label="First name"
                    type="text"
                    style={{backgroundColor: "white"}} 
                  />
                  <TextField
                    id="lname"
                    label="Last name"
                    type="text"
                    style={{backgroundColor: "white"}} 
                  />
                </Grid>
                <Grid item xs={6}>
                  <TextField
                    id="email"
                    label="Email address"
                    type="email"
                    style={{backgroundColor: "white"}} 
                  />
                  <TextField
                    id="pwd"
                    label="Password"
                    type="password"
                    style={{backgroundColor: "white"}} 
                  />
                </Grid>
                <Grid item xs={6}>
                  <select
                    id="gender"
                    style={{ width: "96%", marginLeft: "2%", paddingTop: "15px", paddingBottom: "15px", backgroundColor: "white" }}
                  >
                    <option value="" defaultChecked>-- SELECT GENDER --</option>
                    <option value="M">Male</option>
                    <option value="F">Female</option>
                    <option value="O">Other</option>
                  </select>
                </Grid>
                <Grid item xs={6} style={{ marginLeft: "2%", marginTop: "3%" }}>
                  <input type="file" id="photo" />
                </Grid>
                <Grid item xs={6} style={{ textAlign: "center", marginTop: "5%" }}>
                  <Button onClick={formSubmit} variant="contained" style={{ marginRight: "10px" }}>Register</Button>
                  <Link href="import_export">
                    <Button variant="outlined">Import & Export</Button>
                  </Link>
                </Grid>
              </Grid>
            </form>
            <div style={{ textAlign: "center" }}>
              <p>
                <del>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</del> OR <del>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</del>
              </p>
              <Grid item xs={6} style={{ textAlign: "center", marginTop: "5%" }}>
                <Button onClick={getData} color="success" variant="outlined" style={{ marginRight: "10px" }}>Get Data</Button>
                <Button onClick={deleteData} color="error" variant="outlined">Delete Data</Button>
              </Grid>
            </div>
            {data.length > 0 && 
              <div style={{marginTop: "30px"}}>
                <table>
                  <thead>
                    <th style={{ border: "2px solid black" }}>Name</th>
                    <th style={{ border: "2px solid black" }}>Email</th>
                    <th style={{ border: "2px solid black" }}>Password</th>
                    <th style={{ border: "2px solid black" }}>Gender</th>
                    <th style={{ border: "2px solid black" }}>Photo</th>
                  </thead>
                  <tbody>
                    {data.length > 0 && data.map((item) => {
                      return (
                        <tr>
                          <td style={{ border: "2px solid black" }}>
                            {item.fname} {item.lname}
                          </td>
                          <td style={{ border: "2px solid black", textAlign: "center" }}>
                            {item.email}
                          </td>
                          <td style={{ border: "2px solid black", textAlign: "center" }}>
                            {item.password}
                          </td>
                          <td style={{ border: "2px solid black", textAlign: "center" }}>
                            {item.gender}
                          </td>
                          <td style={{ border: "2px solid black", textAlign: "center" }}>
                            <img src={`http://127.0.0.1:8000/ProfilePhoto/${item.photo}`} alt={item.photo} width="70"/>
                          </td>
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>
            }
          </Box>
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by SAYED
      </footer>
    </div>
  )
}
